### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by derekorgan** [tomekkup/helenos#11]
Dropped the helenos.war file into `tomcat/7.0.35/libexec/webapps/` directory but getting this error when I try login. Looks like a static reference for posting form instead of relative

URL: http://localhost:8080/helenos/gui/

POST http://localhost:8080/j_spring_security_check?nocache=1359625315441 404 (Not Found)

http://cl.ly/image/151f2k3W0m0h

**Comment by tomekkup** [comment]
Could you show me application logs? It seems that app didn't initialized correctly.

**Comment by tomekkup** [comment]
can not confirm. closing.
