### ISSUE TITLE
Default configuration feature

### ISSUE THREAD

**Issue by tomekkup** [tomekkup/helenos#13]
Default connection string is localhost:9160.
 Application fails to start if there is no Cassandra instance running on local host.

**Comment by rgknp** [comment]
Hi,

Any updates on this issue? I am hitting this as I am trying to connect my Cassandra cluster which is on a remote VM.

**Comment by tomekkup** [comment]
already implemented but waiting for release package.

**Comment by Arturo-Wu-Zhou** [comment]
Hi,
I downloaded the latest packages from http://sourceforge.net/projects/helenos-gui/files/ followed the faq and changed default.host property in default.properties. However, no matter what I put as the value for default.host, the application still tries to connect to localhost. The error I get:
WARN  CassandraHostRetryService - Downed localhost(127.0.0.1):9160 host still appears to be down:

**Comment by RMoulet** [comment]
I am having the same problem here with version 1.5 and jetty - modified default.properties, restarted both jetty, then the computer. It still tries to connect to localhost(127.0.0.1):9160.
