### ISSUE TITLE
displays everything as ascii

### ISSUE THREAD

**Issue by rajreddy** [tomekkup/helenos#14]
all data is tried to be displayed as ascii, hence integers and other types don't show up properly.

![image](https://f.cloud.github.com/assets/2848195/717046/db980814-df42-11e2-8d2e-01270062b2e8.png)

**Comment by tomekkup** [comment]
Yeap. I'm thinking about key,value,colname serializers

**Comment by rajreddy** [comment]
clean up..

**Comment by rajreddy** [comment]
clean up. closing..
