### ISSUE TITLE
Multiple Questions and Enhancement Requests

### ISSUE THREAD

**Issue by rahulneel** [tomekkup/helenos#15]
Excellent product, was very easy to install and setup.
1)  The "Clock" cloumn shows time in epoch, was wondering if you could display it in human readable form.
2) Is there a way to make it read only, so the user cant drop/truncate column families/keyspaces?
3) Any idea when you will have 1.4 out?

**Comment by tomekkup** [comment]
1) mmm... interesting. added to wish list
2) implemented - wait for 1.4 rel
3) within 2,3 weeks

**Comment by rahulneel** [comment]
Thanks for the quick response. This is the fastest response I have seen from anyone on GitHub :) I know I am asking a lot of questions, so please respond when you can, no rush.

1) The human readable form for the clock came from another tool that I was looking at (CassandraGUI), that proves to be quiet helpful when trying to look at when a column was updated. 
https://code.google.com/a/apache-extras.org/p/cassandra-gui/

2) Would the readonly option be via a role? Similarly, in the Write mode is there a way to add rows/columns/column families/keyspaces? (again question from seeing similar write functionality in CassandraGUI)

3) Is there a way to get a bunch of rows back randomly, without specifying row ranges or keys?(again question from seeing similar functionality in CassandraGUI, it seems to have a way to just get a 1000 random keys)

4) One more thing I noticed was that the copy to clip board was not working. It shows the option on using Force Luke ;) but does not copy to clip board, nor does it allow me to copy by using ctrl-c. I tried to copy the clock so I could try to convert it to human readable format, externally, but it wouldnt allow.

5) Do you plan to also have deserializers? For example if I byte serialize my data using something like Coherence POF (Portable Object Format), Can I provide my POF configs, Coherence JARs in a certain place and it would be able to deserialize data and display it?

6) Is there a way for me to chose/set/configure the read consistency level I want instead of it using Quorum?

7) Is there a way to move the H2 database from the user's home directory to a user configurable location?

**Comment by tomekkup** [comment]
1) I'll get a bit of inspiration ;)
2) yes... in 1.4 release
3) no or not yet
4) Hmmm... I didn't noticed similar issue... more details needed, browser name and version and set of plugins installed
5) yes. Exactly in the way you've described.
6) in 1.4 release... you can set a CL before querying
7) look into web.xml file, but remind that it can be overwritten after updating to newer version.

**Comment by rahulneel** [comment]
4) Looks like its an issue on my side, I had another person try it from both IE and FireFox and it copied fine. I will try to reproduce the issue and let you know when it happens, but dont think its an issue on your side.

**Comment by tomekkup** [comment]
new release is ready and testing. this week I'll upload package

**Comment by rahulneel** [comment]
I am trying to test the 1.4-RC1 version, will respond after testing it.
