### ISSUE TITLE
Cannot login to Cassandra Cluster

### ISSUE THREAD

**Issue by hsihsa75** [tomekkup/helenos#17]
I have authentication in place for C\* Cluster. Where to provide cassandra user id/details in Helenos. Can you please post sample...
T

**Comment by ernestobv** [comment]
I have the same problem. Any help will be appreciated.
Regards.

**Comment by pasinduu** [comment]
I ran into the same issue and couldn't find a solution. It works fine when I don't have Cassandra authentication setup, but throws a "Invalid Request Exception (why? You have not logged in) when I have authentication setup. Any help would be greatly appreciated. 

Thanks!

**Comment by tomekkup** [comment]
Cluster authentication support will be available in next release. Please wait few days
