### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by belgacea** [tomekkup/helenos#25]
Hi, I have trouble to set up authentication on helenos, is there any config to do ?
I've successfully make it work without authentication, but now I've activated it and set an superuser (same as helenos : admin/admin), I get and error message : 
exceptionTypeName : "me.prettyprint.hector.api.exceptions.HInvalidRequestException"
message : "InvalidRequestException(why:You have not logged in)"
Somebody have correctly set up authentication with helenos ?
Thx

**Comment by Nexolight** [comment]
Not so far. I even can't change the password of admin. Well I can at runtime but as soon as I restart the server it resets itself. I'm using the bundled version.

**Comment by belgacea** [comment]
Sorry, I found out my mistake. Thx
