### ISSUE TITLE
unable to deploy with tomcat 6

### ISSUE THREAD

**Issue by dmdevito** [tomekkup/helenos#3]
helenos.war does not fit well with Tomcat 6

1) servetl-api-2.5.jar included within helenos.war is causing pb 
AFAIK, there is no need to include such JAR into the war, according to the Java EE spec

2) Tomcat is complaining about a duplicated XML element into the web.xml

So, at the end, helenos.war is not usable with Tomcat 6 !

I guess you may have tested the helenos.war according to some appserver.
Could you please update the projet's README to tell the appserver you have used, its version and if possible also, the command-line ?
Thanks.

**Comment by tomekkup** [comment]
agree. Bug fixed. Just uploaded a new version. Try out. I'll update a guide tommorow.
