### ISSUE TITLE
enable users to enter Cassandra config within the 1st Helenos web page

### ISSUE THREAD

**Issue by dmdevito** [tomekkup/helenos#4]
Today, to browse the data of a Cassandra database, users have to change a file "helenos.properties" within WEB-INF directory : it's cumbersome.

Why not defining a form, within the Helenos 1st web page, to let users enter the Cassandra config ? It would be easier to define such config and to let users switch between different databases.
Thanks.

**Comment by tomekkup** [comment]
I had planned to implement this at beginning but it's not easy. I'll keep it in mind.

**Comment by tomekkup** [comment]
fixed
