### ISSUE TITLE
enable users to browse rowkeys

### ISSUE THREAD

**Issue by dmdevito** [tomekkup/helenos#5]
With Cassandra, very offten, the rowkey is a surrogate key: it is not derived from application data.
So, it's difficult, with Helenos, to enter a rowkey to browse its columns, because rowkeys are very often unknown as there are defined within the appserver in front of Cassandra.

It would be easier to offer users an opportunity to browse rowkeys.
Let's say a feature enabling to display the first 100 rowkeys (of a CF) with a 'next' button to offer to display the next 100.
And if the user clicks on a given rowkey, the form to select its columns to be displayed should be shown
Thanks.

**Comment by tomekkup** [comment]
it's already done but I've marked 'paging functionality' as scheduled
