### ISSUE TITLE
authorize empty textfield for defining 'null' as colname limit

### ISSUE THREAD

**Issue by dmdevito** [tomekkup/helenos#6]
Let say I have a rowkey and I want to browse all of its columns
With the current form, I enter the given rowkey and I let the text fields (defining the "start" and "end" columns) as empty: I just hope these empty text fields will be understood as 'null'.

Unfortunately, these empty fields are not understood as 'null'. So, I enter "aaaaaaa" within the "start" text field and "zzzzzzz" within the "end" text fields, and I have got all my columns because there are all beginning with a [a-z] letter.
Well, that is cumbersome, because here, my CF is a simple one with colname being of type UTF8Type, so I can enter "aaaaaaaa" and "zzzzzzz" values that will be correctly understood as UTF8Type.
I would have much more work to define decent "start" and "end" values with other col types, or with a composite column.

So, I think it would be easier for Helenos to understand an empty ("start" or "end") text field as null.
Thanks.

**Comment by tomekkup** [comment]
implemented
