### ISSUE TITLE
authorize users to copy column value(s) resulting from the "search" step

### ISSUE THREAD

**Issue by dmdevito** [tomekkup/helenos#7]
Here is my case: I have entered a rowkey, and searched for columns.
The existing columns have been displayed by Helenos, as expected => good.

I have clicked on a line on screen (a column of the given rowkey) to copy its value and paste it within Notepad++ for example. But unfortunately, after selecting the column value on screen, CTRL-C or right-clicking with my mouse did not enable me to copy the column value as expected.

Could you please enable such a copy ?
Thanks.

**Comment by tomekkup** [comment]
implemented in version 1.1 .
You must double click on cell and type Ctrl+C . In next release it would be a tooltip with hint.
